import snapshot from './generated/config.json'

// A committed, read-only snapshot of the repo's config/*.yaml (the engine's single
// source of truth). The cockpit can't read config/ at runtime — it's a pod app —
// so the Config + Exchanges views render this mirror, regenerated by
// scripts/snapshot_cockpit_config.py. The cockpit NEVER edits config.

export interface ConfigSnapshot {
  source: string
  files: Record<string, unknown>
}

export const CONFIG = snapshot as ConfigSnapshot

export function isObject(v: unknown): v is Record<string, unknown> {
  return v !== null && typeof v === 'object' && !Array.isArray(v)
}

/** Flatten a nested config value to ordered [dot.path, leafValue] pairs. */
export function flatten(value: unknown, prefix = ''): Array<[string, unknown]> {
  if (!isObject(value) && !Array.isArray(value)) return [[prefix, value]]
  const entries: Array<[string, unknown]> = Array.isArray(value)
    ? value.map((v, i) => [String(i), v])
    : Object.entries(value)
  if (!entries.length) return [[prefix, Array.isArray(value) ? '[]' : '{}']]
  const out: Array<[string, unknown]> = []
  for (const [k, v] of entries) {
    const path = prefix ? `${prefix}.${k}` : k
    out.push(...flatten(v, path))
  }
  return out
}
