#!/usr/bin/env python3
"""Snapshot ``config/*.yaml`` into a read-only JSON the cockpit imports.

The cockpit is a Lemma pod app: it reads the pod over the SDK and cannot read the
repo's ``config/`` at runtime. But ``config/`` is the engine's single source of
truth, and the operator wants to *see* the live risk / cost / rigor limits and the
tradable universe. So the Config + Exchanges views render a **committed snapshot**
of the config — a derived, display-only artifact regenerated by this script
whenever the config changes::

    uv run python scripts/snapshot_cockpit_config.py

It writes ``pod/apps/cockpit/source/src/generated/config.json``. The cockpit never
edits config — config changes happen in ``config/`` + PR review (no magic numbers
in code); this is a read-only mirror, clearly labelled with its source + time.
"""

from __future__ import annotations

import datetime
import json
import pathlib

import yaml

ROOT = pathlib.Path(__file__).resolve().parents[1]
CONFIG_DIR = ROOT / "config"
OUT = ROOT / "pod" / "apps" / "cockpit" / "source" / "src" / "generated" / "config.json"

# The config files the cockpit surfaces (display-only). venues.yaml is a skeleton
# today (the registry is populated as adapters land); an empty file → null.
FILES = ["risk", "costs", "rigor", "instruments", "venues", "discovery", "portfolio", "research"]


def main() -> None:
    files: dict[str, object] = {}
    for name in FILES:
        path = CONFIG_DIR / f"{name}.yaml"
        files[name] = yaml.safe_load(path.read_text()) if path.exists() else None

    snapshot = {
        "generated_at": datetime.datetime.now(datetime.UTC).isoformat(timespec="seconds"),
        "files": files,
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(snapshot, indent=2, default=str, ensure_ascii=False) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
